name: weather_track
description: Weather Track

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.0

  # Network connectivity
  connectivity_plus: ^2.3.6+1
  
  # Local cache
  hive: ^2.2.3

  # HTTP Client
  uno: ^1.0.1+3

  # Service locator and routing
  flutter_modular: ^5.0.3

  # Path utilities
  path_provider: ^2.0.11
  
  # UI
  animations: ^2.0.4
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  faker: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true